# Generated by Django 4.2.11 on 2024-03-22 08:52

import apiv1.interfaces
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0002_user_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_message_notifications', models.BooleanField(default=True)),
                ('receive_mention_notifications', models.BooleanField(default=True)),
                ('receive_friend_request_notifications', models.BooleanField(default=True)),
                ('notification_delivery_method', models.CharField(choices=[('push', 'Push Notifications'), ('email', 'Email'), ('sms', 'SMS')], default='push', max_length=50)),
                ('profile_visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('friends_only', 'Friends Only')], default='public', max_length=50)),
                ('allow_friend_requests', models.BooleanField(default=True)),
                ('allow_messages_from', models.CharField(choices=[('everyone', 'Everyone'), ('friends_only', 'Friends Only'), ('no_one', 'No One')], default='everyone', max_length=50)),
                ('display_online_status', models.BooleanField(default=True)),
                ('theme_preference', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('custom', 'Custom')], default='light', max_length=50)),
                ('font_size', models.CharField(default='medium', max_length=20)),
                ('font_style', models.CharField(default='normal', max_length=20)),
                ('display_language', models.CharField(default='English', max_length=50)),
                ('message_notification_sound', models.CharField(default='default', max_length=100)),
                ('event_notification_sound', models.CharField(default='default', max_length=100)),
                ('two_factor_authentication', models.BooleanField(default=False)),
                ('mute_group_chat_notifications', models.BooleanField(default=False)),
                ('leave_group_on_exit', models.BooleanField(default=False)),
                ('enable_read_receipts', models.BooleanField(default=True)),
                ('enable_typing_indicators', models.BooleanField(default=True)),
                ('auto_archive_chats', models.BooleanField(default=False)),
                ('auto_archive_period', models.IntegerField(default=30)),
                ('auto_download_media', models.BooleanField(default=True)),
                ('media_quality_preference', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('backup_chat_history', models.BooleanField(default=True)),
                ('sync_across_devices', models.BooleanField(default=True)),
                ('blocked_words', models.TextField(default='')),
                ('account_deletion_confirmation', models.BooleanField(default=True)),
                ('account_deletion_recovery_email', models.EmailField(blank=True, max_length=200, null=True)),
                ('account_deactivation', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('block_users', models.ManyToManyField(related_name='blocked_users', to='apiv1.user')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='apiv1.user')),
            ],
            bases=(models.Model, apiv1.interfaces.JsonInterface),
        ),
    ]
