# Generated by Django 4.2.11 on 2024-03-22 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0004_remove_usersettings_user_usersettings_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='sync_across_devices',
        ),
    ]
