# Generated by Django 4.2.11 on 2024-03-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0005_remove_usersettings_sync_across_devices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='account_deactivation',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='account_deletion_confirmation',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='account_deletion_recovery_email',
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='block_users',
            field=models.ManyToManyField(null=True, related_name='blocked_users', to='apiv1.user'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='blocked_words',
            field=models.TextField(default='', null=True),
        ),
    ]
