# Generated by Django 4.2.11 on 2024-03-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0007_remove_usersettings_block_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='block_users',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='blocked_words',
            field=models.CharField(default=''),
        ),
    ]
